### ISSUE TITLE
panic: runtime error: slice bounds out of range [:100] with capacity 32

### ISSUE THREAD

**Issue by voigtjm** [mrwiora/NAMEinator#55]
Hi - got a "panic: runtime error: slice bounds out of range [:100] with capacity 32"

Steps:
Downloaded [NAMEinator_0.0.5_windows_amd64.tar.gz](https://github.com/mrwiora/NAMEinator/releases/download/v0.0.5/NAMEinator_0.0.5_windows_amd64.tar.gz)

Windows 11 Cmd (admin) prompt:
D:\Downloads>mkdir NAMEinator

D:\Downloads>tar -xvzf "D:\Downloads\NAMEinator_0.0.5_windows_amd64.tar.gz" -C d:\downloads\NAMEinator
x README.md
x NAMEinator.exe

Manually created datasrc directory (as per other issues on wiki)
D:\Downloads\NAMEinator>mkdir datasrc

Manually created Alexa-top-2000-domains.txt and nameserver-globals.csv

Attempted to run:
D:\Downloads\NAMEinator>nameinator
starting NAMEinator - version 0.0.5
understood the following configuration: {numberOfDomains:100 debug:false contest:true nameserver:}
-------------
NOTE: as this is an alpha - we rely on feedback - please report bugs and featurerequests to https://github.com/mwiora/NAMEinator/issues and provide this output
OS: windows ARCH: amd64
-------------
trying to load nameservers from datasrc/nameserver-globals.csv
trying to load domains from datasrc/alexa-top-2000-domains.txt
panic: runtime error: slice bounds out of range [:100] with capacity 32

goroutine 1 [running]:
main.prepareBenchmarkDomains(0xc00007a9c0, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/mwiora/NAMEinator/loader.go:33 +0x1eb
main.prepareBenchmark(0xc00007a990, 0x0, 0x0, 0x0, 0xc00007a9c0, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/mwiora/NAMEinator/main.go:127 +0x67
main.main()
        /home/travis/gopath/src/github.com/mwiora/NAMEinator/main.go:164 +0xad

Also tried running the command as follows:
D:\Downloads\NAMEinator>nameinator -nameserver 192.168.1.1
starting NAMEinator - version 0.0.5
understood the following configuration: {numberOfDomains:100 debug:false contest:true nameserver:192.168.1.1}
-------------
NOTE: as this is an alpha - we rely on feedback - please report bugs and featurerequests to https://github.com/mwiora/NAMEinator/issues and provide this output
OS: windows ARCH: amd64
-------------
trying to load domains from datasrc/alexa-top-2000-domains.txt
panic: runtime error: slice bounds out of range [:100] with capacity 32

goroutine 1 [running]:
main.prepareBenchmarkDomains(0xc00007a9f0, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/mwiora/NAMEinator/loader.go:33 +0x1eb
main.prepareBenchmark(0xc00007a9c0, 0x0, 0x0, 0x0, 0xc00007a9f0, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/mwiora/NAMEinator/main.go:127 +0x67
main.main()
        /home/travis/gopath/src/github.com/mwiora/NAMEinator/main.go:164 +0xad

**Comment by papypaprika** [comment]
> Hi - got a "panic: runtime error: slice bounds out of range [:100] with capacity 32"

Same here on linux aarch64 :(
