### ISSUE TITLE
panic: runtime error: index out of range [1] with length 1

### ISSUE THREAD

**Issue by kzoli429** [mrwiora/NAMEinator#56]
OS: linux ARCH: amd64
-------------
trying to load nameservers from datasrc/nameserver-globals.csv
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
main.readNameserversFromFile({0xc00010abd0, {{0x0, 0x0}, 0x0, 0x0, 0x0, 0x0}}, {0x555cd8904fde?, 0x0?})
	NAMEinator/loader.go:52 +0x3c5
main.prepareBenchmarkNameservers({0xc00010abd0, {{0x0, 0x0}, 0x0, 0x0, 0x0, 0x0}})
	NAMEinator/loader.go:17 +0xec
main.prepareBenchmark({0xc00010abd0, {{0x0, 0x0}, 0x0, 0x0, 0x0, 0x0}}, {0xc00010ac00, {{0x0, 0x0}, ...}})
	NAMEinator/main.go:126 +0x118
main.main()
	NAMEinator/main.go:164 +0x97

**Comment by Clausinho** [comment]
try `cd $(mktemp -d) && git clone https://github.com/mwiora/NAMEinator . && nameinator` in bash
Source: https://aur.archlinux.org/packages/nameinator

related to #52 and #55 

I guess #43 fixes it? but @mrwiora doesn't seem to be maintaining this project anymore

**Comment by MountainX** [comment]
I installed [AUR (en) - nameinator](https://aur.archlinux.org/packages/nameinator)
To work around this error, I had to extract the tar file and cd to the parent directory of datasrc/
Simple steps, but it means nameinator can only be run from this directory.
```
tar -xf NAMEinator-0.0.5.tar.gz
cd NAMEinator-0.0.5/
$ nameinator
```

**Comment by articuno1au** [comment]
This is caused the AUR package not including the config files for the application.

For anyone else running into this, you can simply do the following
```
cd ~/Downloads
mkdir datasrc
cd datasrc
wget https://raw.githubusercontent.com/mrwiora/NAMEinator/master/datasrc/alexa-top-2000-domains.txt
wget https://raw.githubusercontent.com/mrwiora/NAMEinator/master/datasrc/nameserver-globals.csv
```
You can edit both the files to add/remove servers and test domains. Only gotcha here is that you need to run nameinator while in ~/Downloads (or wherever you might choose to save those config files).

**Comment by batot1** [comment]
True, when running nameinator in Download directory working correctly.

**Comment by jnpn** [comment]
If people are curious, I added flags to specify path for domains and nameservers here https://github.com/jnpn/NAMEinator/tree/nicer_flag

I too ran in the AUR issue.

**Comment by rafaelcastan** [comment]
> This is caused the AUR package not including the config files for the application.
> 
> For anyone else running into this, you can simply do the following
> 
> ```
> cd ~/Downloads
> mkdir datasrc
> cd datasrc
> wget https://raw.githubusercontent.com/mrwiora/NAMEinator/master/datasrc/alexa-top-2000-domains.txt
> wget https://raw.githubusercontent.com/mrwiora/NAMEinator/master/datasrc/nameserver-globals.csv
> ```
> 
> You can edit both the files to add/remove servers and test domains. Only gotcha here is that you need to run nameinator while in ~/Downloads (or wherever you might choose to save those config files).

The datasrc folder need to be at the same directory as the NAMEinator script

![image](https://user-images.githubusercontent.com/56899689/218076730-f1ddd6cc-4029-47dd-9405-719983821116.png)

**Comment by articuno1au** [comment]
> > This is caused the AUR package not including the config files for the application.
> > For anyone else running into this, you can simply do the following
> > ```
> > cd ~/Downloads
> > mkdir datasrc
> > cd datasrc
> > wget https://raw.githubusercontent.com/mrwiora/NAMEinator/master/datasrc/alexa-top-2000-domains.txt
> > wget https://raw.githubusercontent.com/mrwiora/NAMEinator/master/datasrc/nameserver-globals.csv
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You can edit both the files to add/remove servers and test domains. Only gotcha here is that you need to run nameinator while in ~/Downloads (or wherever you might choose to save those config files).
> 
> The datasrc folder need to be at the same directory as the NAMEinator script:
> 
> ![image](https://user-images.githubusercontent.com/56899689/218076730-f1ddd6cc-4029-47dd-9405-719983821116.png)

No, it needs to be in the execution directory. If you execute the script from the same directory it's housed in, that will work. You can easily validate by testing the steps I've provided.

**Comment by rafaelcastan** [comment]
@articuno1au strange, for me it only worked after I put it together with the script, maybe it's because I was running from the directory

**Comment by rafaelcastan** [comment]
@articuno1au you are right I have run the code from other dir, I deleted my comment to not make any confusion to other people, thanks

**Comment by articuno1au** [comment]
No worries man. We're all just trying to help out people :)

**Comment by iconoclasthero** [comment]
https://raw.githubusercontent.com/mrwiora/NAMEinator/master/datasrc/nameserver-globals.csv:
```
8.8.8.8,google-public-dns-a.google.com.,US
8.8.4.4,google-public-dns-b.google.com.,US
208.67.222.222,resolver1.opendns.com.,US
2001:470:20::2,ordns.he.net.,US
156.154.71.1,rdns2.ultradns.net.,US
216.146.35.35,resolver1.dyndnsinternetguide.com.,US
1.1.1.1,one.one.one.one.,US
1.0.0.1,one.one.one.one.,US
```
If these aren't enough servers to test, you need to add to this list.
