### ISSUE TITLE
panic: runtime error: index out of range [1] with length 1

### ISSUE THREAD

**Issue by batot1** [mrwiora/NAMEinator#58]
~]$ nameinator
starting NAMEinator - version custom
understood the following configuration: {numberOfDomains:100 debug:false contest:true nameserver:}
-------------
NOTE: as this is an alpha - we rely on feedback - please report bugs and featurerequests to https://github.com/mwiora/NAMEinator/issues and provide this output
OS: linux ARCH: amd64
-------------
trying to load nameservers from datasrc/nameserver-globals.csv
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
main.readNameserversFromFile({0xc00009abd0, {{0x0, 0x0}, 0x0, 0x0, 0x0, 0x0}}, {0x55e42d3d7fde?, 0x0?})
	NAMEinator/loader.go:52 +0x3c5
main.prepareBenchmarkNameservers({0xc00009abd0, {{0x0, 0x0}, 0x0, 0x0, 0x0, 0x0}})
	NAMEinator/loader.go:17 +0xec
main.prepareBenchmark({0xc00009abd0, {{0x0, 0x0}, 0x0, 0x0, 0x0, 0x0}}, {0xc00009ac00, {{0x0, 0x0}, ...}})
	NAMEinator/main.go:126 +0x118
main.main()
	NAMEinator/main.go:164 +0x97

**Comment by batot1** [comment]
duplicate isssue
