### ISSUE TITLE
panic error

### ISSUE THREAD

**Issue by gliom** [mrwiora/NAMEinator#59]
Hello.
I run nameinator (on my distro is named so) and I got the following:
```
starting NAMEinator - version custom
understood the following configuration: {numberOfDomains:100 debug:false contest:true nameserver:}
trying to load nameservers from datasrc/nameserver-globals.csv
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
main.readNameserversFromFile({0xc000182ba0, {{0x0, 0x0}, 0x0, 0x0, 0x0, 0x0}}, {0x55ce298b81d7?, 0x0?})
	NAMEinator/loader.go:52 +0x3e5
main.prepareBenchmarkNameservers({0xc000182ba0, {{0x0, 0x0}, 0x0, 0x0, 0x0, 0x0}})
	NAMEinator/loader.go:17 +0xec
main.prepareBenchmark({0xc000182ba0, {{0x0, 0x0}, 0x0, 0x0, 0x0, 0x0}}, {0xc000182bd0, {{0x0, 0x0}, ...}})
	NAMEinator/main.go:126 +0x118
main.main()
	NAMEinator/main.go:164 +0x97
```

Other info:
OS: Garuda Linux x86_64
Shell: fish 3.6.0
Terminal: xfce4-terminal
Package: https://aur.archlinux.org/packages/nameinator (compiled from source)

**Comment by mabod** [comment]
Do you have that file: `datasrc/nameserver-globals.csv` ? It needs to be in that exact subdirectory "datasrc".

Example file:

```
8.8.8.8,google,
1.1.1.1,cloudflare,
9.9.9.9,quad9,
208.67.222.222,openDNS,
84.200.69.80,DNSwatch,
```
